schema_version = 7

[devices."serial:2207lz51mjw8"]
dpi = 2500

[devices."serial:2207lz51mjw8".identity]
display_name = "MX Master 3S"
codename = "MX Master 3S"
kind = "mouse"

[app_settings]
launch_at_login = true
check_for_updates = true
auto_install_updates = false
update_prompt_seen = true
show_in_menu_bar = true
capture_mouse_events = true
smooth_scroll = false
vertical_scroll_sensitivity = 14
app_icon = "openlogi"
auto_download_assets = true
asset_source = "automatic"
thumbwheel_sensitivity = 14
appearance = "system"
ui_scale = "normal"
device_view_mode = "grid"

[devices."serial:2207lz51mjw8".identity.model_info]
entity_count = 3
unit_id = [
    0,
    0,
    0,
    0,
]
model_ids = [
    45108,
    0,
    0,
]
extended_model_id = 0

[devices."serial:2207lz51mjw8".identity.model_info.transports]
usb = false
equad = false
btle = true
bluetooth = false

[devices."serial:2207lz51mjw8".identity.capabilities]
buttons = true
pointer = true
lighting = false
scroll_inversion = true
hires_wheel = true
thumbwheel = true
haptic_feedback = false
haptic_panel = false

[devices."serial:2207lz51mjw8".links."receiver:dbd03d07e7f2c6a9:slot:2".capabilities]
buttons = true
pointer = true
lighting = false
scroll_inversion = true
hires_wheel = true
thumbwheel = true
haptic_feedback = false
haptic_panel = false

[devices."serial:2207lz51mjw8".bindings.GestureButton]
Up = "MissionControl"
Down = "ShowDesktop"
Left = "PreviousDesktop"
Right = "NextDesktop"
Click = "MissionControl"

[keyboard]
